### ISSUE TITLE
Error when entering an arena

### ISSUE THREAD

**Issue by h0rns0fwh1t3dr4g0n** [Arxareon/MovementSpeed#13]
![WoWScrnShot_043024_155535](https://github.com/Arxareon/MovementSpeed/assets/168272364/774dbe49-a7e1-4223-87db-c0325a9f36fd)

This Lua error after every entering of arena with both custom preset and "under the minimap" preset. doing /reload causing same error

**Comment by Arxareon** [comment]
Thank you for the report! I'm very busy at the moment and have been working on a big update for a while now. In the meantime, I will consider pushing out a hotfix for this beforehand if I can't finish the big update soon.

**Comment by Arxareon** [comment]
Yes, so good news, there is a very easy hotfix for this. However, I will not make a separate release for this before the next big update (I'll of course include the fix in that), instead, you can apply the fix manually in the meantime if you need it.

It's not too difficult, open the following file in your World of Warcraft install folder: `[World of Warcraft install folder]\_retail_\Interface\Addons\MovementSpeed\Main.lua` in a text editor and insert this line of code at line 338 in-between the following lines of code like so:
```lua
	map.id = C_Map.GetBestMapForUnit("player")
	if not map.id then return end
	map.name = C_Map.GetMapInfo(map.id).name
```

Alternatively, here's the file with the hotfix. You can download it from here (link below - I have to zip it to send it, you may extract it) and replace Main.lua in this folder: `[World of Warcraft install folder]\_retail_\Interface\Addons\MovementSpeed`
**[Main.zip](https://github.com/Arxareon/MovementSpeed/files/15170968/Main.zip)**

If you need assistance, feel free to get back to me!
