### ISSUE TITLE
Movement Speed problems

### ISSUE THREAD

**Issue by Dyrebear** [Arxareon/MovementSpeed#16]
the speed frame has disappeared
/movespeed does nothing.
I tried reinstalling

**Comment by Arxareon** [comment]
Thanks for the report, the addon got broken by changes made by Blizzard in patch 10.0.2. I'm on it! It will be addressed in the next addon update (currently in testing)!

**Comment by WybeBosch** [comment]
@Arxareon Looking forward to the new release !  :)

**Comment by Arxareon** [comment]
The latest beta version is here: [Movement Speed 3.0 Test F (Release candidate)](https://github.com/Arxareon/MovementSpeed/releases/tag/3.0_Test_F)

I'll do a full release in a couple of days (after making any quick changes/fixes as needed).
