### ISSUE TITLE
Time for 3.0 Test F?

### ISSUE THREAD

**Issue by b-morgan** [Arxareon/MovementSpeed#18]
Current WoW versions are 110005, 40401, 11504 and I believe that updating the .toc files is all that is needed.

**Comment by Arxareon** [comment]
Hi! Thanks for the reminder!

I'm actually inching lose to a full release, hence I didn't feel the need to release a Test F. I'll do testing myself and if most things seem to be in order, it'll be a regular release. If not, I'll do a beta as Test F.

**Comment by Arxareon** [comment]
It's here: [Movement Speed 3.0 Test F (Release candidate)](https://github.com/Arxareon/MovementSpeed/releases/tag/3.0_Test_F)

I decided to release  it as beta for now to make sure there isn't much I've missed. I'll wait a couple of days for testing and then I'll do a full release (after making any quick changes/fixes as needed).
