### ISSUE TITLE
Update for 3.4.1 and 10.0.5

### ISSUE THREAD

**Issue by b-morgan** [Arxareon/MovementSpeed#2]
Can we please get an update for 3.4.1 and 10.0.5.

**Comment by Arxareon** [comment]
Thank you for taking interest!

I'm actively working on the update but it will take a moment to finish. I expect to be able to release it ~~this weekend~~*. Fingers crossed!

*_Sorry, it had to be this next weekend. Well, hopefully. Stay tuned!_

**Comment by Arxareon** [comment]
@b-morgan The update has now been released. Sorry for the delays.
[Movement Speed 2.4](https://github.com/Arxareon/MovementSpeed/releases/tag/2.4)
