### ISSUE TITLE
Patch 10.1 - WidgetTools Error #1 - This one makes it unusable, because it's a flood of errors causing lag

### ISSUE THREAD

**Issue by Raiukage** [Arxareon/MovementSpeed#5]
Message: Interface/SharedXML/SharedUIPanelTemplates.lua:555: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
Time: Tue May  2 22:27:19 2023
Count: 3029
Stack: Interface/SharedXML/SharedUIPanelTemplates.lua:555: attempt to perform arithmetic on field 'cursorOffset' (a nil value)
[string "@Interface/SharedXML/SharedUIPanelTemplates.lua"]:555: in function `ScrollingEdit_OnUpdate'
[string "@Interface/SharedXML/SecureUIPanelTemplates.lua"]:190: in function <Interface/SharedXML/SecureUIPanelTemplates.lua:189>

Locals: self = EditBox {
 0 = <userdata>
 Instructions = FontString {
 }
 handleCursorChange = true
}
elapsed = 0.017000
scrollFrame = WidgetToolsAboutAboutChangelogScrollFrame {
 0 = <userdata>
 scrollBarX = -10
 maxLetters = 0
 TopTex = Texture {
 }
 scrollBarBottomY = -3
 MiddleTex = Texture {
 }
 LeftTex = Texture {
 }
 BottomLeftTex = Texture {
 }
 scrollBarTopY = -1
 EditBox = EditBox {
 }
 BottomTex = Texture {
 }
 scrollBarHideIfUnscrollable = true
 BottomRightTex = Texture {
 }
 TopLeftTex = Texture {
 }
 ScrollBar = Frame {
 }
 TopRightTex = Texture {
 }
 CharCount = FontString {
 }
 RightTex = Texture {
 }
}
height = 192
range = 0
scroll = 0
size = 192
cursorOffset = nil
(*temporary) = nil
(*temporary) = WidgetToolsAboutAboutChangelogScrollFrame {
 0 = <userdata>
 scrollBarX = -10
 maxLetters = 0
 TopTex = Texture {
 }
 scrollBarBottomY = -3
 MiddleTex = Texture {
 }
 LeftTex = Texture {
 }
 BottomLeftTex = Texture {
 }
 scrollBarTopY = -1
 EditBox = EditBox {
 }
 BottomTex = Texture {
 }
 scrollBarHideIfUnscrollable = true
 BottomRightTex = Texture {
 }
 TopLeftTex = Texture {
 }
 ScrollBar = Frame {
 }
 TopRightTex = Texture {
 }
 CharCount = FontString {
 }
 RightTex = Texture {
 }
}
(*temporary) = 0
(*temporary) = "attempt to perform arithmetic on field 'cursorOffset' (a nil value)"

**Comment by Arxareon** [comment]
Thanks for the reports, I'm actively working on the 10.1 update - hopefully to be released tomorrow once I can sort everything out. If not, it could take a couple of days but with any luck it won't reach into the weekend.

Sorry for the wait and thanks for your patience!

**Comment by Arxareon** [comment]
- #6
- #7
- #8

**Comment by Arxareon** [comment]
Combined with the follow-ups:
- #6
- #7
- #8

**Comment by Arxareon** [comment]
Solved with the latest release: [Movement Speed 2.6](https://github.com/Arxareon/MovementSpeed/releases/tag/2.6)
