### ISSUE TITLE
Bug: Widget Tools blocked from an action....

### ISSUE THREAD

**Issue by nancikennedy** [Arxareon/MovementSpeed#9]
Getting the dreaded "xx has been blocked from an action only available to the Blizzard UI. You can disable..." 

BugGrabber:
1x [ADDON_ACTION_FORBIDDEN] AddOn 'WidgetTools' tried to call the protected function 'SpellStopCasting()'.
[string "@!BugGrabber/BugGrabber.lua"]:480: in function <!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SpellStopCasting'
[string "@FrameXML/UIParent.lua"]:4109: in function `ToggleGameMenu'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:336: in function `TransitionBackOpeningPanel'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:325: in function `ExitWithCommit'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:301: in function `Close'
[string "@SharedXML/Settings/Blizzard_SettingsPanel.lua"]:71: in function <SharedXML/Settings/Blizzard_SettingsPanel.lua:70>

Locals:
_ = Frame {
 RegisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 0 = <userdata>
 UnregisterEvent = <function> defined @!BugGrabber/BugGrabber.lua:486
 SetScript = <function> defined @!BugGrabber/BugGrabber.lua:486
}
event = "ADDON_ACTION_FORBIDDEN"
events = <table> {
 ADDON_ACTION_BLOCKED = <function> defined @!BugGrabber/BugGrabber.lua:552
 ADDON_ACTION_FORBIDDEN = <function> defined @!BugGrabber/BugGrabber.lua:552
 PLAYER_LOGIN = <function> defined @!BugGrabber/BugGrabber.lua:546
 LUA_WARNING = <function> defined @!BugGrabber/BugGrabber.lua:561
 ADDON_LOADED = <function> defined @!BugGrabber/BugGrabber.lua:506
}

**Comment by Arxareon** [comment]
Sigh. Thanks for the report and the helpful error message! The new Dragonflight Settings panel has been griefing me beyond belief trying to work with (or more like around) it.

I'll definitely try to wrestle with it some more. No ETA and I might need follow-up info, we'll see.

**Comment by Arxareon** [comment]
It seems that I can't really find something I'm explicitly doing wrong and it is likely a bug/oversight of the base UI (it appears to be related to using the default pop-up windows - but, given the error message it is connected to the Settings panel).

That said, I will try to see if I can find some workaround (like perhaps building and use some kind of custom pop-up windows or something) or optimization I haven't thought of.. or find something that I am indeed doing wrong but just haven't noticed..

But, my main suspicion is that Blizzard will have to get around to fixing this one.

**Comment by nancikennedy** [comment]
You might want to take a look at/get in touch with https://github.com/AcidWeb/REHack. He had issues with rehack triggering problems related to the settings panel for his addon. I don't know what he did to resolve it, but the problem stopped after one of his updates a couple of months ago.

**Comment by Arxareon** [comment]
Okay, so I did find something (unrelated to what issues REHack appeared to have - but thanks for the tip!). It was related to how I added the small addon logos in the list of the Settings AddOns tab. It turns out I haven't changed the method from what I used pre-Dragonflight and that one no longer appears to be safe. Luckily that's a very easy fix.

@nancikennedy In fact, here is a test package. If you have some time, could you perhaps install it and give it a test for me?
[MovementSpeed-2.7_Test.zip](https://github.com/Arxareon/MovementSpeed/files/11444501/MovementSpeed-2.7_Test.zip)

**Comment by nancikennedy** [comment]
Doing that now...

**Comment by nancikennedy** [comment]
So far, I have not received any errors. I spent time just doing all sorts of options stuff and then opening/closing it again. I've just randomly played and then messed with options. All with no errors.

**Comment by Arxareon** [comment]
Awesome! Thanks for taking the time to help me with the testing!

**Comment by nancikennedy** [comment]
I'm always glad to help out when I can. :)
